### ISSUE TITLE
question list string 오류

### ISSUE THREAD

**Issue by jeonjw95** [devdynam0507/StackUnderFlow#5]
http://localhost:8080/api/v1/issue/content/list/0
api로 리스트를 받아오면 title과 content가 ???????로 표기된다.

**Comment by devdynam0507** [comment]
# 이슈 확인바람
일단 utf8mb4로 안되있어서 그랬던거같고 설정 다시해서 docker hub에 올려놨으니 buildrun.sh 다시 실행해보삼. 
utf8mb4로 해주는 이유는 이모지때문

# 설정파일은 다음과 같다
> /etc/mysql/mysql.conf.d/mysqld.cnf  
 
### mysqld.cnf
[client]
default-character-set=utf8mb4

[mysql]
default-character-set=utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
user            = mysql
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
port            = 3306
basedir         = /usr
datadir         = /var/lib/mysql
tmpdir          = /tmp
lc-messages-dir = /usr/share/mysql
skip-external-locking
